### ISSUE TITLE
librccl.so.1: No such file or directory

### ISSUE THREAD

**Issue by aruno14** [Grench6/RX580-rocM-tensorflow-ubuntu20.4-guide#1]
I followed your instruction on Ubuntu 20.4.1, but when I test python code, I got the below error:

`ImportError: librccl.so.1: cannot open shared object file: No such file or directory`

**Comment by aruno14** [comment]
`export LD_LIBRARY_PATH="/opt/rocm-3.5.1/rccl/lib/"` solved the error.

**Comment by Grench6** [comment]
Sorry for late response. I am glad you solved the problem. 😀

**Comment by aruno14** [comment]
I think your reply was very fast :)
Thank you for your guide, it realy helped me!
