### ISSUE TITLE
how to open video card permission to all users

### ISSUE THREAD

**Issue by MOLOjl** [Grench6/RX580-rocM-tensorflow-ubuntu20.4-guide#12]
hello, there
I followed your guide and installed ROCm on my server, I was trying to find a way to apply the same function these two commands do to every user on this server(even those who will join in the future).
```
sudo usermod -a -G video $LOGNAME
sudo usermod -a -G render $LOGNAME
``` 
I don't know much about Linux, please help me.

**Comment by whytox** [comment]
This should address your problem!
https://askubuntu.com/questions/1269337/error-while-processing-rock-dkms-and-rocm-dkms

**Comment by Grench6** [comment]
@MOLOjl Its been a while, so I am closing this up in hopes the answer provided by @whytox has been helpful to you.
