### ISSUE TITLE
apt-key certificate not valid

### ISSUE THREAD

**Issue by MarkusvonStaden** [Grench6/RX580-rocM-tensorflow-ubuntu20.4-guide#5]
I have to use 
`wget -q -O - http://repo.radeon.com/rocm/apt/debian/rocm.gpg.key | sudo apt-key add -`
instead of
`wget -q -O - http://repo.radeon.com/rocm/apt/3.5.1/rocm.gpg.key | sudo apt-key add -`
otherwise I get an error, when doing `apt update`, saying that the certificate is not valid.

Maybe you can help me on another problem as well. My default kernel is 5.4.0-81 and I cannot downgrade to 5.4.0-42. If I do so, my keyboard stops working and my second screen stays black. But I think this is why I can't get ROCm to work.

**Comment by Grench6** [comment]
Hi, which Ubuntu version are you using?

**Comment by MarkusvonStaden** [comment]
20.04
I just found my mistake. I screwed up my kernel downgrade.
