### ISSUE TITLE
GPG Key error 

### ISSUE THREAD

**Issue by tichondrius2215** [Grench6/RX580-rocM-tensorflow-ubuntu20.4-guide#7]
After adding repository, GPG Key error is show while running `sudo apt update`. I think its the issue from rocm as I tried same steps for 3.7 repository too and got same error.

`Get:11 http://repo.radeon.com/rocm/apt/3.5.1 xenial InRelease [1,819 B]     
Err:11 http://repo.radeon.com/rocm/apt/3.5.1 xenial InRelease
  The following signatures were invalid: EXPKEYSIG 9386B48A1A693C5C James Adrian Edwards (ROCm Release Manager) <JamesAdrian.Edwards@amd.com>
Reading package lists... Done
W: GPG error: http://repo.radeon.com/rocm/apt/3.5.1 xenial InRelease: The following signatures were invalid: EXPKEYSIG 9386B48A1A693C5C James Adrian Edwards (ROCm Release Manager) <JamesAdrian.Edwards@amd.com>
E: The repository 'http://repo.radeon.com/rocm/apt/3.5.1 xenial InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`
PS: I downgraded kernel from 5.11.0 to 5.4.0-42-generic.

**Comment by Grench6** [comment]
Yes, this is definitively an issue that must be fixed in _their_ side. It seems the certificate has expired and they haven't renewed it yet. You could just wait for them to do so, or you could simply bypass the verification.

**Comment by Grench6** [comment]
Yep, I just checked and the key expired on 2021-08-01. 
I don't know if they plan on updating it, but for now you can either bypass verification or use [this key](https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x9386b48a1a693c5c).

Let me know if it works.

**Comment by Grench6** [comment]
I identified the error on the guide. I used a link to a key that wont get updated. I am fixing it now.
The correct link is `https://repo.radeon.com/rocm/apt/debian/rocm.gpg.key`(instead of `http://repo.radeon.com/rocm/apt/3.5.1/rocm.gpg.key`).

**Comment by tichondrius2215** [comment]
Yes I did that correction before adding the PPA to list. Now rocm and tensorflow both are working as expected. Thanks for putting up all the info together..
