### ISSUE TITLE
Kernel restarts in Spyder and Jupyter notebook.

### ISSUE THREAD

**Issue by tichondrius2215** [Grench6/RX580-rocM-tensorflow-ubuntu20.4-guide#9]
The installation worked as expected for few days but later the kernel restarted while trying to train models like resent. I did a fresh installation of Ubuntu and then rocm but issue still remains. Interesting thing is the benchmark test works as expected with same tensorflow-rocm with GPU. Benchmark script also works in Spyder. 

This is the last line of running my own resent model as python script ( without spyder or jupyter-notebook).

`2021-09-22 00:27:52.519822: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libMIOpen.so
  1/114 [..............................] - ETA: 0s - loss: 66690.9219 - accuracy: 0.0312Memory access fault by GPU node-1 (Agent handle: 0x5cd9760) on address 0x500000000. Reason: Page not present or supervisor privilege.
Aborted (core dumped)`

While benchmark test gives this output. The overall images/second values is also low. Could this be a hardware issue?

`Done warm up
Step	Img/sec	total_loss
1	images/sec: 43.8 +/- 0.0 (jitter = 0.0)	7.731
10	images/sec: 43.8 +/- 0.1 (jitter = 0.0)	8.055
20	images/sec: 43.8 +/- 0.0 (jitter = 0.0)	7.789
30	images/sec: 43.8 +/- 0.0 (jitter = 0.1)	7.974
40	images/sec: 43.8 +/- 0.0 (jitter = 0.1)	7.578
50	images/sec: 43.8 +/- 0.0 (jitter = 0.1)	7.568
60	images/sec: 43.9 +/- 0.0 (jitter = 0.1)	7.821
70	images/sec: 43.9 +/- 0.0 (jitter = 0.1)	7.802
80	images/sec: 43.9 +/- 0.0 (jitter = 0.1)	7.790
90	images/sec: 43.9 +/- 0.0 (jitter = 0.1)	8.034
100	images/sec: 43.9 +/- 0.0 (jitter = 0.1)	8.026
----------------------------------------------------------------
total images/sec: 43.86
----------------------------------------------------------------
`

**Comment by Grench6** [comment]
Hi, I can barely remember a *similar* bug (back when I used rocm), but I don't think it has something to do with the installation.
I can't be of help since I don't know how to fix this nor I have any pointers to useful info...

Good luck and let us know if you manage to fix it!

**Comment by tichondrius2215** [comment]
Yeah agree that the issue is unrelated to installation. It seems to be issue with certain types of models like resnet. I am testing different models with varying structures and I am able to run simple sequential models of CNN and LSTM.. There doesn't seems to be a definite issue so closing this thread. Thanks again.
